---
title: "EDA&Modeling"
author: "Ziyi Bai"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("ggplot2","tidyverse","rstanarm","dplyr","pwr","MASS","arm","corrgram","lme4")
```

## Import Data
```{r}
setwd("/Users/baiziyi/Desktop/MSSP/MA678/midterm project")
sephora <- read.csv("sephora.csv")
```

## Data Cleaning
```{r}
#randomly choose 10 categories products 
sephora$sum <- sephora$online_only + sephora$exclusive + sephora$limited_edition + sephora$limited_time_offer
sephora$sum <- as.numeric(sephora$sum)
```

## Initial EDA 
```{r pressure, echo=FALSE}
library(corrgram)
corre <- subset(sephora,select = c("id","brand","rating","love","number_of_reviews","price","online_only","exclusive","limited_edition","limited_time_offer","sum"))
corre <- data.frame(corre)
corrgram(corre,order=TRUE,lower.panel=panel.shade,upper.panel=panel.pie,text.panel=panel.txt,main="Correlation Of Sephora Intercorrelations")
```

```{r}
unique(sephora$category)
#randomly choose 10 categories products 
love <- sephora %>% filter(category=="Perfume"|category=="Lipstick"|category=="Shampoo"|category=="Anti-Aging"|category=="Face Masks"|category=="Eye Brushes"|category=="Eyeshadow"|category=="Hair Oil"|category=="Shaving"|category=="Candles")
#add how many types of promotion way into dataset, named as sum
```

```{r}
#count sum 
length(which(love[,22]==0))
length(which(love[,22]==1))
length(which(love[,22]==2))
length(which(love[,22]==3))
length(which(love[,22]==4))
```

## Further EDA
### 1.How many love products recevie in total of different category 
```{r}
category1 <- aggregate(love~category,data = love, FUN = mean)
category2 <- aggregate(rating~category,data = love, FUN = mean)
category3 <- aggregate(price~category,data = love, FUN = mean)
category4 <- aggregate(sum~category,data = love, FUN = mean)

left_join(category1,category2,c("category"="category")) -> category
left_join(category3,category, c("category"="category")) -> category
left_join(category4,category, c("category"="category")) -> category

category %>% 
  mutate(category=fct_reorder(category,love)) %>%
  ggplot(aes(x=category,y=love+price,fill=category)) +
  geom_col(position="dodge")+
  labs(title="Average Number Of Love For 10 Cosmetic Products") +
  xlab("Category") +
  ylab("Average Number Of Love") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 13, face = "bold"))
```

### 2. Boxplot of love group by whether have promotion way or not
```{r}
ggplot(data=love,aes(x=category,y=love,fill=factor(sum)))+
  geom_boxplot(outlier.colour=NA,notch=F)+
  labs(title="Boxplot of Love For Products With Different Number Of Promotion Ways",x="Category",y="Number Of Love Receives")+
  theme(plot.title = element_text(size = 13),
        axis.text = element_text(size =  14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size=6)) +
  theme(plot.title = element_text(hjust = 0.5))+
  coord_cartesian(ylim = c(0, 125000))+
  labs(fill="Number Of Promotion Ways")+
  scale_fill_discrete(labels= c('0','1','2','3','4'))
```

### 3.Price
```{r}
#How the love change with the increase of price
love %>% 
  mutate(category=fct_reorder(category,love)) %>%
ggplot(aes(x=price,y=love,colour=category))+
  geom_point()+
  facet_wrap(~category)+
  labs(title = "How the love change with the increase of price")
```

### 4.Rating 
```{r}
#How the love change with the increase of rating
love %>% 
  mutate(category=fct_reorder(category,love)) %>%
ggplot(aes(x=rating,y=love,colour=category))+
  geom_point()+
  facet_wrap(~category)+
  labs(title = "How the love change with the increase of rating")
```

## Modeling
### 1. Plot each variable 
```{r}
#look at the distribution
#hist(love$rating,col="pink")
#hist(love$price,col="orange")
#hist(love$number_of_reviews,col="lightgreen",breaks = 3)
#hist(love$sum,col="purple",breaks=3)

#look at the potential relationship between love and chosen independent variables
par(mfrow=c(2,2))
ggplot(aes(x=price,y=love),data=love)+
  geom_jitter()+
  scale_x_log10()
ggplot(aes(x=number_of_reviews,y=love),data=love)+
  geom_jitter()+
  scale_y_log10()+
  scale_x_log10()
ggplot(aes(x=sum,y=love),data=love)+
  geom_jitter()+
  scale_x_log10()+
  scale_y_log10()
ggplot(aes(x=rating,y=love),data=love)+
  geom_jitter()+
  scale_x_log10()

ggplot(aes(x=rating+price+sum,y=love),data=love)+
  geom_jitter()+
  scale_y_log10()+
  scale_x_log10()
```

### 2. Fit models
```{r}
#fit poisson model
fit1 <- stan_glm(love~price+sum+rating+category,family=poisson(link = "log"),data=love,refresh=0)
print(summary(fit1),digits=3)
saveRDS(fit1,"fit1.rds")
#test over-dispersion
library(qcc)
qcc.overdispersion.test(love$love,type="poisson")
#I do have the problem of over-dispersion 
```

```{r}
#so I fit quasi-poisson model
fit2 <- glm(love~price+sum+rating+category,family=quasipoisson(link = "log"),data=love)
print(summary(fit2),digits=3)
```

```{r}
#fit neg_binomial_2 model
fit3 <- stan_glm(love~price+sum+rating+category,family=neg_binomial_2(link = "log"),data=love,refresh=0)
saveRDS(fit3,"fit3.rds")
print(summary(fit3),digits=3)
```

```{r}
#fit glmer model 
fit4 <- glmer(love~price+sum+rating+(1|category)+(1|id),family=poisson(link="log"),data=love)
print(summary(fit4))

invlogit(8.1921193)
invlogit(0.0013805)
invlogit(0.5613717)
invlogit(0.0886627)
```

```{r}
#use log(number_of_reviews+1) as offset
fit5 <- stan_glm(love~price+sum+rating+category,family=neg_binomial_2,offset=log(number_of_reviews+1),data=love,refresh=0)
print(summary(fit5))
#this one fits not well so I don't include it in the main part.
```

## Check internal validation 
```{r}
par(mfrow=c(2,2))
plot(fit2)
plot(fit3)
plot(fit4)
lattice::dotplot(ranef(fit4,condVar = TRUE))
```

```{r}
#binned residual plot
par(mfrow=c(2,2))
residuals(fit1)
binnedplot(fitted(fit1),resid(fit1))

residuals(fit2)
binnedplot(fitted(fit2),resid(fit2))

residuals(fit3)
binnedplot(fitted(fit3),resid(fit3))

residuals(fit4)
binnedplot(fitted(fit4),resid(fit4))
```

```{r}
#install.packages("effects")
library(effects)
plot(allEffects(fit4))
```

```{r}
#CI
n <- length(love$love)
estimate <- mean(love$love)
se <- sd(love$love)/sqrt(n)
int95 <- estimate + qt(c(0.025,0.975),n-1)*se

confint(fit4,level=0.95)

#pred.int <- predict(fit1,interval = "prediction")
#new <- cbind(love,pred.int)
#p <- ggplot(new,aes(x=price+sum+rating,y=love))+
#geom_point()+
  #stat_smooth(method = stan_glm)
#p+geom_line(aes(y=lwr),color="red",linetype="dashed")+
  #geom_line(aes(y=upr),color="red",linetype="dashed")
#outlier
qqnorm(love$love)
qqline(love$love,col=2,lwd=2)
qqplot(love$price, love$love, col="blue",qq.lines="red")
```




